CREATE DATABASE Employee_Data;
USE Employee_Data;

CREATE TABLE Employee (
    EID INT NOT NULL,
    EJoining_Date DATE NOT NULL,
    EName VARCHAR(50) NOT NULL,
    EPhone_Number BIGINT NOT NULL,
    EDOB DATE NOT NULL,
    EAddress VARCHAR(200) NOT NULL,
    EPost VARCHAR(20) NOT NULL,
    ESalary INT NOT NULL,
    PRIMARY KEY (EID)
);
